
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: "security-enforcer.example.com"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  variables:
    - name: containerCount
      expression: "size(object.spec.template.spec.containers)"
    - name: containersWithSecurityContext
      expression: |
        has(object.spec.template.spec.containers) ?
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
          .filter(idx, idx < variables.containerCount)
          .filter(idx, has(object.spec.template.spec.containers[idx].securityContext))
        : []
  mutations:
  - patchType: "JSONPatch"
    jsonPatch:
      expression: |
        variables.containersWithSecurityContext.map(idx, 
          JSONPatch{
            op: 'add',
            path: '/spec/template/spec/containers/' + string(idx) + '/securityContext/privileged',
            value: false
          }
        ) +
        variables.containersWithSecurityContext.map(idx, 
          JSONPatch{
            op: 'add',
            path: '/spec/template/spec/containers/' + string(idx) + '/securityContext/allowPrivilegeEscalation',
            value: false
          }
        )
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: "security-enforcer-binding.example.com"
spec:
  policyName: "security-enforcer.example.com"
