apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-website-example
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - path: tools/crossplane/website
      repoURL: https://github.com/dag-andersen/kubecon-us-2025-code.git
      targetRevision: main