apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-compositions
  namespace: flux-system
spec:
  interval: 1m
  path: "./tools/crossplane/compositions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default