apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: apps.example.my-domain.io
spec:
  scope: Namespaced
  group: example.my-domain.io
  names:
    kind: App
    plural: apps
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            image:
              description: The container image.
              type: string
          required:
          - image
        status:
          type: object
          properties:
            replicas:
              description: The number replicas.
              type: integer
            address:
              description: The app's IP address.
              type: string