apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: my-app
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
            selector: matchLabels: {
              "app.oam.dev/component": context.name
            }
            template: {
              metadata: labels: {
                "app.oam.dev/component": context.name
              }
              spec: {
                containers: [{
                  name:  context.name
                  image: parameter.image
                  ports: [{
                    containerPort: parameter.port
                  }]
                }]
              }
            }
          }
        }
        
        outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          spec: {
            selector: {
              "app.oam.dev/component": context.name
            }
            ports: [{
              port:       parameter.port
              targetPort: parameter.port
            }]
          }
        }
        
        parameter: {
          image: string
          port:  *80 | int
        }