apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: compositions
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane/flux/resources/compositions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubecon-repo
  targetNamespace: default