apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubecon-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/dag-andersen/kubecon-us-2025-code.git