apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-definitions
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: kubevela/argocd/resources/kubevela-definitions
      repoURL: https://github.com/dag-andersen/kubecon-us-2025-code.git
      targetRevision: main