apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/dag-andersen/kubecon-us-2025-code
  password: GITHUB_TOKEN
  username: not-used